# Stable configuration
edition = "2021"
newline_style = "Unix"
use_small_heuristics = "Max"
unstable_features = true

# Width and alignment  
max_width = 80
hard_tabs = false
tab_spaces = 4
indent_style = "Block"
wrap_comments = true

# Imports
imports_indent = "Block"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true

# Consistency
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true

# Style
binop_separator = "Front"
overflow_delimited_expr = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 20
struct_lit_single_line = false

# Misc
chain_width = 50
fn_params_layout = "Tall"
match_arm_blocks = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true
